name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build & Test Node.js App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  docker-build:
    name: Build Docker Image
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t knight_board:latest .

  docker-push:
    name: Push Docker Image
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag knight_board:latest ${{ secrets.DOCKER_USERNAME }}/knight_board:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/knight_board:latest

  deploy:
    name: Deploy to Server (Optional)
    needs: docker-push
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/knight_board:latest
            docker stop knight_board || true
            docker rm knight_board || true
            docker run -d -e BOARD_API=${{ secrets.BOARD_API }} -e COMMANDS_API=${{ secrets.COMMANDS_API }} --name knight_board -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/knight_board:latest
